services:
  devsecops-demo-api:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: devsecops-demo-api-staging
    ports:
      - "${APP_PORT}:8000"
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: 8000
      FEATURE_FLAG_DEMO: ${FEATURE_FLAG_DEMO}
      API_TOKEN: ${API_TOKEN}
    restart: unless-stopped